### ISSUE TITLE
Exclude certain terms from /item command input

### ISSUE THREAD

**Issue by Zukunftsmusik** [PieInTheSky-Inc/YaDc#283]
* `mki`
* `mkii`
* `mkiii`

**Comment by architelos** [comment]
Opened a PR to fix this, unless you want to keep mks higher than III

**Comment by Zukunftsmusik** [comment]
Merged the PR, then went a different route. The `/item` command will now throw an error, when too many results (more than 50, makes 2 embeds) are being returned.
Implemented with v1.4.0.0
