### ISSUE TITLE
/targets fleets max_highest_trophies fails

### ISSUE THREAD

**Issue by pieps** [PieInTheSky-Inc/YaDc#303]
`/targets fleets max_highest_trophies` fails when `min_trophies` and `max_trophies`are not specified:

```
Type Error
'<' not supported between instances of 'NoneType' and 'int'
```

Additionally, when `min_trophies` and `max_trophies` are specified, a comparison of `min_trophies` and `max_highest_trophies` is backwards:

```
Value Error
The specified highest trophy count for a player must not be lower than the specified minimum trophy count.
```

**Comment by Zukunftsmusik** [comment]
Fixed with v1.4.1.2 thanks to your PR <3
