### ISSUE TITLE
Change output of `/prestige` command

### ISSUE THREAD

**Issue by Zukunftsmusik** [PieInTheSky-Inc/YaDc#37]
Make the output if the `/prestige` command shorter by condensing recipes with the same result.

Example: ![Image](https://i.imgur.com/JawTNaX.jpg)

**Comment by arkblaze27** [comment]
@Zukunftsmusik I made a PR for this issue:
https://github.com/PieInTheSky-Inc/YaDc/pull/38

**Comment by Zukunftsmusik** [comment]
Implemented for v1.2.3.1
