### ISSUE TITLE
The `/room` command does not include damage output

### ISSUE THREAD

**Issue by Avandr0p-VforVendetta** [PieInTheSky-Inc/YaDc#44]
add categories if it is applicable to that weapon, like emp duration, volley, crew damage, and stuff like that because it isnt listed now

**Comment by Zukunftsmusik** [comment]
Things like that should actually be displayed for all weapon rooms (except missile rooms and Ion Cannon), but aren't currently, due to a bug. I'll look into it.

**Comment by Avandr0p-VforVendetta** [comment]
oh okay

**Comment by Zukunftsmusik** [comment]
Fixed for version 1.2.4.0-beta
