### ISSUE TITLE
Add command `/sales`

### ISSUE THREAD

**Issue by Avandr0p-VforVendetta** [PieInTheSky-Inc/YaDc#66]
/sales, which lists the daily sales available to be bought from the website for the last 30 days, sorted by reverse chronology, i.e. oldest last, since the page automatically scrolls to the bottom of last message, and thus one sees the oldest near expiry items first, which is usually what one wants to check out

**Comment by Zukunftsmusik** [comment]
`/sales` to just print the latest 30 days of sales
`/sales <object_name>` to lookup sales for a given item or crew

**Comment by Zukunftsmusik** [comment]
Added functionality to record daily sales with v1.3.0.0

**Comment by Zukunftsmusik** [comment]
Added with v1.3.1.4
